[workspace]
resolver = "2"
members = [
  "crates/sl-mpc-mate",
  "crates/sl-oblivious",
  "crates/sl-paillier",
  "crates/sl-mpc-traits",
  "crates/sl-verifiable-enc",
]

[profile.bench]
debug = true
