[registries]
silencelaboratories = { index = "ssh://git@ssh.shipyard.rs/silencelaboratories/crate-index.git" }

[net]
git-fetch-with-cli = true

[registry]
global-credential-providers = ["cargo:token", "cargo:macos-keychain", "cargo:wincred"]